// import "./globals.css";
// import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';
// import { ThemeProvider } from '@mui/material/styles';
// import CssBaseline from '@mui/material/CssBaseline';
// import theme from '@/theme/theme'
// import { AuthProvider } from '@/contexts/AuthProvider'
import { AuthContextProvider } from '@/context/AuthContext';
// import { Toaster } from "react-hot-toast";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* <AppRouterCacheProvider> */}
        <AuthContextProvider>
          {/* <ThemeProvider theme={theme}> */}
            {/* <CssBaseline /> */}
            <body>{children}</body>
          {/* </ThemeProvider> */}
        </AuthContextProvider>
        {/* <Toaster /> */}
      {/* </AppRouterCacheProvider> */}
    </html>
  );
}
