import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';
import { ThemeProvider } from '@mui/material/styles';
import CssBaseline from '@mui/material/CssBaseline';
import theme from '@/theme/theme'
import { AuthContextProvider } from '@/context/AuthContext';
import { Toaster } from "react-hot-toast";

export const metadata = {
  title: "Logo Quiz App",
  description: "Generated by Los practicantes",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AppRouterCacheProvider>
          <AuthContextProvider>
            <ThemeProvider theme={theme}>
              <CssBaseline />
              {children}
            </ThemeProvider>
          </AuthContextProvider>
          <Toaster />
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
